### ISSUE TITLE
Add abillity to change any color to gradient!

### ISSUE THREAD

**Issue by bleudev** [bleudev/qw#6]
Now we have ability to change any color's `fg` and `bg`. I suggest to add ability to set gradient to `fg` and `bg`. Using this systax:
```yaml
# just color
fg: grey 

# gradient
fg:
  - "#ff0000"
  - "#aa0000"
```
